#ifndef __HAVE_CONFIG_H
#define __HAVE_CONFIG_H

#define LED_STATUS_PIO     IOCON_PIO1_0
#define LED_STATUS_PORT    1
#define LED_STATUS_PIN     0
#define LED_INVERTED_LOGIC false

#define TXE_PIO      IOCON_PIO0_7
#define TXE_PORT     0
#define TXE_PIN      7
#define TXE_CONFIG   IOCON_MODE_INACT | IOCON_FUNC0

#define RXE_PIO      IOCON_PIO0_4
#define RXE_PORT     0
#define RXE_PIN      4
#define RXE_CONFIG   (IOCON_FUNC0)

#define EXT_PIO      IOCON_PIO0_3
#define EXT_PORT     0
#define EXT_PIN      3
#define EXT_CONFIG   (IOCON_FUNC0 | IOCON_MODE_PULLUP | IOCON_DIGMODE_EN)

#define TONE_PIO     IOCON_PIO0_8
#define TONE_PORT    0
#define TONE_PIN     8

#define TONE_SW_PIO  IOCON_PIO0_5
#define TONE_SW_PORT 0
#define TONE_SW_PIN  5

#define TX_READY_DELAY_MS 150

#define TONE_DEFAULT_HZ  900
#define TONE_EXT_HZ      440

#define MORSE_SHORT_DURATION_MS 80
#define MORSE_LONG_DURATION_MS  (MORSE_SHORT_DURATION_MS * 3)
#define MORSE_PAUSE_DURATION_MS (MORSE_SHORT_DURATION_MS * 3)
#define MORSE_SPACE_DURATION_MS (MORSE_SHORT_DURATION_MS * 7)

#define CALL_INTERVAL_SEC   30
#define CALL_DELAY_AFTER_TX 10
#define CALL_STRING         "ON0LBN"
#define CALL_POST_DELAY_MS  100

#define ROGER_BEEP_DELAY_MS    440
#define ROGER_BEEP_DURATION_MS 250

#define WDT_TIMEOUT_SEC        45

#endif /* __HAVE_CONFIG_H */
